export const DDD77_CITIES = [
  "Abaíra",
  "Anagé",
  "Angical",
  "Aracatu",
  "Baianópolis",
  "Barra da Estiva",
  "Barra do Choça",
  "Barreiras",
  "Belo Campo",
  "Boa Nova",
  "Bom Jesus da Lapa",
  "Bom Jesus da Serra",
  "Boquira",
  "Botuporã",
  "Brejolândia",
  "Brotas de Macaúbas",
  "Brumado",
  "Buritirama",
  "Caatiba",
  "Caculé",
  "Caetanos",
  "Caetité",
  "Canápolis",
  "Candiba",
  "Cândido Sales",
  "Caraíbas",
  "Carinhanha",
  "Catolândia",
  "Caturama",
  "Cocos",
  "Condeúba",
  "Contendas do Sincorá",
  "Cordeiros",
  "Coribe",
  "Correntina",
  "Cotegipe",
  "Cristópolis",
  "Dom Basílio",
  "Encruzilhada",
  "Érico Cardoso",
  "Feira da Mata",
  "Formosa do Rio Preto",
  "Guajeru",
  "Guanambi",
  "Ibiassucê",
  "Ibicoara",
  "Ibipitanga",
  "Ibitiara",
  "Ibotirama",
  "Igaporã",
  "Ipupiara",
  "Iramaia",
  "Itambé",
  "Itapetinga",
  "Ituaçu",
  "Iuiú",
  "Jaborandi",
  "Jacaraci",
  "Jussiape",
  "Lagoa Real",
  "Licínio de Almeida",
  "Livramento de Nossa Senhora",
  "Luís Eduardo Magalhães",
  "Macarani",
  "Macaúbas",
  "Maetinga",
  "Maiquinique",
  "Malhada",
  "Malhada de Pedras",
  "Mansidão",
  "Matina",
  "Mirante",
  "Morpará",
  "Mortugaba",
  "Muquém de São Francisco",
  "Novo Horizonte",
  "Oliveira dos Brejinhos",
  "Palmas de Monte Alto",
  "Paramirim",
  "Paratinga",
  "Piatã",
  "Pindaí",
  "Piripá",
  "Planalto",
  "Poções",
  "Presidente Jânio Quadros",
  "Riachão das Neves",
  "Riacho de Santana",
  "Ribeirão do Largo",
  "Rio de Contas",
  "Rio do Antônio",
  "Rio do Pires",
  "Santa Maria da Vitória",
  "Santa Rita de Cássia",
  "Santana",
  "São Desidério",
  "São Félix do Coribe",
  "Sebastião Laranjeiras",
  "Serra do Ramalho",
  "Serra Dourada",
  "Sítio do Mato",
  "Tabocas do Brejo Velho",
  "Tanhaçu",
  "Tanque Novo",
  "Tremedal",
  "Urandi",
  "Vitória da Conquista",
  "Wanderley",
] as const;

export type Ddd77City = (typeof DDD77_CITIES)[number];
